version: '2'

services:

  redis:
      image: "bitnami/redis:latest"
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      labels:
        kompose.service.type: nodeport
      ports:
        - "6379:6379"
      volumes:
        - "redis_data:/bitnami/redis"

  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"

  kafka:
      image: "wurstmeister/kafka"
      ports:
        - "9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "aTestTopic:1:1"
        KAFKA_DELETE_TOPIC_ENABLE: "true"
        KAFKA_BROKER_ID: 100
      volumes:
        - "kafka_data:/var/run/docker.sock"
      depends_on:
        - zookeeper

  collaboration-rest-server:
        build:
          context: ..
          dockerfile: collaboration-platform/collaboration-rest-server.dockerfile
        ports:
          - "8080:8080"
        volumes:
          - "collaboration-rest-server_logs:/opt/applications/logs"
        depends_on:
          - redis
          - kafka

  collaboration-event-consumer:
        build:
          context: ..
          dockerfile: collaboration-platform/collaboration-event-consumer.dockerfile
        ports:
          - "8081:8080"
        volumes:
          - "collaboration-consumer_logs:/opt/applications/logs"
        depends_on:
          - redis
          - kafka

volumes:
    redis_data:
      driver: local
    kafka_data:
      driver: local
    collaboration-rest-server_logs:
      driver: local
    collaboration-consumer_logs:
      driver: local
